services:

  nginx:
    container_name: tp-symfony-nginx
    image: nginx:latest
    ports:
      - "8787:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: tp-symfony-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  mysql:
    container_name: tp-symfony-mysql
    image: mysql:8
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/lego_store.sql:/docker-entrypoint-initdb.d/lego_store.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lego_store

  phpmyadmin:
    container_name: tp-symfony-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8788:80"
    depends_on:
      - mysql

volumes:
  database: