<?php

namespace ContainerYhcYo3I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegoControllerhomeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TinoS1V.App\Controller\LegoController::home()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TinoS1V.App\\Controller\\LegoController::home()'] = ($container->privates['.service_locator.TinoS1V'] ?? $container->load('get_ServiceLocator_TinoS1VService'))->withContext('App\\Controller\\LegoController::home()', $container);
    }
}
