<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxa2BnX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxa2BnX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxa2BnX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJxa2BnX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxa2BnX\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jxa2BnX',
    'container.build_id' => 'defe420f',
    'container.build_time' => 1739983232,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxa2BnX');
