<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLn4RRnH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLn4RRnH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLn4RRnH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLn4RRnH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLn4RRnH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ln4RRnH',
    'container.build_id' => '76f02685',
    'container.build_time' => 1739982267,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLn4RRnH');
