<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU5xmIe3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU5xmIe3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU5xmIe3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU5xmIe3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU5xmIe3\App_KernelDevDebugContainer([
    'container.build_hash' => 'U5xmIe3',
    'container.build_id' => '10dcde1b',
    'container.build_time' => 1739378151,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU5xmIe3');
